# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-08T08:47:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "535cf23e310fd86d70303c4fb4f0d81dda6b9f98",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
